// _id: (string) (default id generated by mongoDB)
// title: (string)
// description: (string, default to empty string)
// completed: (boolean, default to: false)
// created_at: (date, default to current date)
// updated_at: (date, default to current date)

var mongoose = require('../config/mongoose');

var TaskSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      minlength: [3, 'Your title must be longer than 3 characters.'],
    },
    description: { type: String, default: '' },
    completed: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Task', TaskSchema);
